package theFridge.controller;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.VBox;

import javafx.scene.shape.Circle;

public class AdminPageController {
	@FXML
	private VBox donationVbox;
	@FXML
	private Circle logout;

	// Event Listener on Circle[#logout].onMouseClicked
	@FXML
	public void logout(MouseEvent event) {
		// TODO Autogenerated
	}
}
