package theFridge.controller;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Circle;

public class CaloriesCalculatorController {
	@FXML
	private Circle profileCircle;
	@FXML
	private AnchorPane Anchor;
	@FXML
	private VBox naviPreview;
	@FXML
	private VBox navi;
	@FXML
	private VBox homeScene;
	@FXML
	private VBox recipeScene;
	@FXML
	private VBox compostScene;
	@FXML
	private VBox foodScene;
	@FXML
	private VBox quizScene;
	@FXML
	private VBox prizeScene;
	@FXML
	private ScrollPane Scrollpane;
	
	@FXML
	public void initialize() throws IOException{
		
		Node root = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
		Node root1 = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
		Node root2 = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
		
		//~Receives methodB from FoodCalculatorCaloriesCalculatorRecipe
		VBox vbox = new VBox(root, root1, root2);	
		Scrollpane.setContent(vbox);
		Scrollpane.setStyle("-fx-background-color:transparent;");
	}
	
	@FXML
	public void showUserDropdown(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void showNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void hideNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void deleteRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
}
