package theFridge.controller;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.ScrollPane;

import javafx.scene.layout.AnchorPane;

import javafx.scene.input.MouseEvent;

import javafx.scene.shape.Circle;

import javafx.scene.layout.VBox;
import javafx.scene.image.ImageView;
import javafx.scene.control.Label;

public class CaloriesCalculatorController {
	@FXML
	private Circle profileCircle;
	@FXML
	private AnchorPane Anchor;
	@FXML
	private VBox naviPreview;
	@FXML
	private VBox navi;
	@FXML
	private VBox homeScene;
	@FXML
	private VBox recipeScene;
	@FXML
	private VBox compostScene;
	@FXML
	private VBox foodScene;
	@FXML
	private VBox quizScene;
	@FXML
	private VBox prizeScene;
	@FXML
	private ScrollPane Scrollpane;
	
	@FXML
	public void initialize() throws IOException{
		//~Receives methodB from FoodCalculatorCaloriesCalculatorRecipe
		VBox vbox = new VBox(update1, update2, update3);	
		Scrollpane.setContent(vbox);
		Scrollpane.setStyle("-fx-background-color:transparent;");
	}
	
	@FXML
	public void showUserDropdown(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void showNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void hideNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void deleteRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
}
