package theFridge.controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

import javafx.scene.control.Label;

import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;

public class FoodCalculatorCaloriesCalculatorRecipeController {
	@FXML
	private Label Time;
	@FXML
	private Label NumberOfCalories;
	@FXML
	private Label Measurements;
	@FXML
	private Label FoodName;
	@FXML
	private ImageView FoodImage;
	@FXML 
	private VBox Recipe;
	
	@FXML
	public void initialize(){
		Time.setText(/*methodA()*/);
		NumberOfCalories.setText(/*methodA()*/);
		Measurements.setText(/*methodA()*/);
		FoodName.setText(/*methodA()*/);
		FoodImage.setText(/*methodA()*/);
		
		//methodB(Recipe);
	}
	
	@FXML
	public void deleteRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
}
