package theFridge.controller;

import javafx.fxml.FXML;

import javafx.scene.layout.HBox;
import javafx.stage.Stage;

import com.jfoenix.controls.JFXButton;

import javafx.event.ActionEvent;
import javafx.scene.Node;
import javafx.scene.image.ImageView;

import javafx.scene.input.MouseEvent;

public class ManualEnterPageController {
	@FXML
	private ImageView deleteBtn;
	@FXML
	private HBox addItemHbox;
	@FXML
	private JFXButton closeBtn;
	@FXML
	private JFXButton submitbtn;

	// Event Listener on ImageView[#deleteBtn].onMouseClicked
	@FXML
	public void deleteItem(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on HBox[#addItemHbox].onMouseClicked
	@FXML
	public void addItem(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on JFXButton[#closeBtn].onAction
	@FXML
	public void closeStage(ActionEvent event) {
		Stage stage = (Stage) ((Node) event.getSource()).getScene().getWindow();
		stage.close();
	}
	// Event Listener on JFXButton[#submitbtn].onAction
	@FXML
	public void submitFoodItems(ActionEvent event) {
		// TODO Autogenerated
	}
}
