package theFridge.controller;

import javafx.fxml.FXML;

import javafx.scene.layout.AnchorPane;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.VBox;

public class Quiz1Controller {
	@FXML
	private AnchorPane Anchor;
	@FXML
	private VBox naviPreview;
	@FXML
	private VBox navi;
	@FXML
	private VBox homeScene;
	@FXML
	private VBox recipeScene;
	@FXML
	private VBox compostScene;
	@FXML
	private VBox foodScene;
	@FXML
	private VBox quizScene;
	@FXML
	private VBox prizeScene;

	// Event Listener on VBox[#naviPreview].onMouseEntered
	@FXML
	public void showNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#navi].onMouseExited
	@FXML
	public void hideNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#homeScene].onMouseClicked
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#recipeScene].onMouseClicked
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#compostScene].onMouseClicked
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#foodScene].onMouseClicked
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#quizScene].onMouseClicked
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#prizeScene].onMouseClicked
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
}
