package theFridge.controller.UGLYNoControllerToo;

import javafx.fxml.FXML;

import javafx.scene.input.MouseEvent;

import javafx.scene.layout.VBox;

public class AddRecipeController {
	@FXML
	private VBox naviPreview;
	@FXML
	private VBox navi;
	@FXML
	private VBox homeScene;
	@FXML
	private VBox recipeScene;
	@FXML
	private VBox compostScene;
	@FXML
	private VBox naviPreview1;
	@FXML
	private VBox foodScene;
	@FXML
	private VBox quizScene;
	@FXML
	private VBox prizeScene;
	@FXML
	private VBox navi1;
	@FXML
	private VBox homeScene1;
	@FXML
	private VBox recipeScene1;
	@FXML
	private VBox compostScene1;
	@FXML
	private VBox foodScene1;
	@FXML
	private VBox quizScene1;
	@FXML
	private VBox prizeScene1;

	// Event Listener on VBox[#naviPreview].onMouseEntered
	@FXML
	public void showNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox[#navi1].onMouseExited
	@FXML
	public void hideNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
}
