package theFridge.controller.foodCalculator;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.control.ScrollPane;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.scene.layout.VBox;
import javafx.scene.shape.Circle;
import theFridge.model.FoodCalculatorCaloriesCalculatorRecipeModel;

public class CaloriesCalculatorController {
	@FXML
	private Circle profileCircle;
	@FXML
	private AnchorPane Anchor;
	@FXML
	private VBox naviPreview;
	@FXML
	private VBox navi;
	@FXML
	private VBox homeScene;
	@FXML
	private VBox recipeScene;
	@FXML
	private VBox compostScene;
	@FXML
	private VBox foodScene;
	@FXML
	private VBox quizScene;
	@FXML
	private VBox prizeScene;
	@FXML
	private ScrollPane Scrollpane;
	
	FoodCalculatorCaloriesCalculatorRecipeModel model;
	
	@FXML
	public void initialize() throws IOException{
		VBox vbox = null;
		int meals = CaloriesCalculatorInputController.NumOfMeals;
		System.out.println("MainCon Meals: " + meals);
		if(meals == 1){
			Node breakfast = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
			vbox = new VBox(breakfast);	
		}
		else if(meals == 2){
			Node breakfast = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
			Node lunch = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/LunchCalories.fxml"));
			vbox = new VBox(breakfast, lunch);	
		}
		else if(meals == 3){
			Node breakfast = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
			Node lunch = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/LunchCalories.fxml"));
			Node dinner = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/DinnerCalories.fxml"));
			vbox = new VBox(breakfast, lunch, dinner);	
		}
		/*
		else if(meals >= 4){
			Node breakfast = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/FoodCalculatorCaloriesCalculatorRecipe.fxml"));
			Node lunch = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/LunchCalories.fxml"));
			for(int i = 0; i < meals; i++){
				Node dinner = (Node)FXMLLoader.load(getClass().getResource("/theFridge/view/foodCalculator/DinnerCalories.fxml"));
			}
		}
		*/
		
		//~Receives methodB from FoodCalculatorCaloriesCalculatorRecipe
		Scrollpane.setContent(vbox);
		Scrollpane.setStyle("-fx-background-color:transparent;");
	}
	
	@FXML
	public void showUserDropdown(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void showNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void hideNavigation(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void changeScene(MouseEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void deleteRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
}
