package theFridge.controller.foodCalculator;

import javafx.fxml.FXML;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

import javafx.event.ActionEvent;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;
import theFridge.model.FoodCalculatorCaloriesCalculatorRecipeModel;

public class FoodCalculatorCaloriesCalculatorRecipeController {
	@FXML
	private Label Time;
	@FXML
	private Label NumberOfCalories;
	@FXML
	private Label Measurements;
	@FXML
	private Label FoodName;
	@FXML
	private ImageView FoodImage;
	@FXML 
	private VBox Recipe;
	
	@FXML
	public void initialize() throws FileNotFoundException{
		ArrayList<Integer>hi = new ArrayList<Integer>();
		File file = new File("src/theFridge/Files/Recipes.txt");
		Scanner sc = new Scanner(file);
		sc.useDelimiter("~");
		while(sc.hasNextInt()){
			hi.add(sc.nextInt());
		}
		int numberOfServings = 0;
		sc.close();
		//int meals = NumMeals.getText();
		//for(int i = 0; i < meals; i++){}
		
		FoodCalculatorCaloriesCalculatorRecipeModel abc = new FoodCalculatorCaloriesCalculatorRecipeModel(1);
		
		//if(meals <=0){
		//	System.out.print("Number must be at least 1");
		//}
		//else if(meals == 1){
			Time.setText("Breakfast");
		//}
		
		NumberOfCalories.setText("Calories: " + abc.getRecipeCalories());
		Measurements.setText(numberOfServings + " Serving");
		FoodName.setText(abc.getRecipeName());
		Image image = new Image(abc.getRecipeImage());
		FoodImage.setImage(image);
		
	}
	
	@FXML
	public void deleteRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
}
