package theFridge.controller.foodCalculator;

import java.io.FileNotFoundException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.image.ImageView;
import javafx.scene.layout.VBox;

public class FoodCalculatorCaloriesCalculatorRecipeController {
	@FXML
	private Label Time;
	@FXML
	private Label NumberOfCalories;
	@FXML
	private Label Measurements;
	@FXML
	private Label FoodName;
	@FXML
	private ImageView FoodImage;
	@FXML 
	private VBox Recipe;
	
	@FXML
	public void initialize() throws FileNotFoundException{
		
	}
	
	@FXML
	public void deleteRecipe(ActionEvent event) {
		// TODO Autogenerated
	}
}
